# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  #adapter: sqlite3
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  adapter: postgresql
  database: pinterest
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: pinterest
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: pinterest
  pool: 5
  timeout: 5000